import globals from "globals";

/** @type {import("eslint").Linter.Config[]} */
export default [
  {
    files: ["site/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        // App modules — still accessed via window.X globals during transition.
        // These will be removed progressively as imports replace global refs.
        ApiClient: "readonly",
        AppRoutes: "readonly",
        AppSelectors: "readonly",
        AppStore: "readonly",
        AuthWidget: "readonly",
        BallPicker: "readonly",
        BoxesView: "readonly",
        BrowserSurface: "readonly",
        BuildEditor: "readonly",
        BuildFingerprint: "readonly",
        BuildUIHelpers: "readonly",
        DataManager: "readonly",
        DataRepositories: "readonly",
        DetailEditorSurface: "readonly",
        DetailHeroSection: "readonly",
        DetailSubjectVM: "readonly",
        DetailViewerSurface: "readonly",
        DomainMappers: "readonly",
        EvConvert: "readonly",
        ExportUI: "readonly",
        FilterToolbar: "readonly",
        FormErrors: "readonly",
        FormFields: "readonly",
        FormMetadata: "readonly",
        InstanceMetadataSection: "readonly",
        InventoryView: "readonly",
        LearnsetService: "readonly",
        MoveEditorWidget: "readonly",
        PokemonViewer: "readonly",
        PresetService: "readonly",
        ProgressIndicator: "readonly",
        ReferenceData: "readonly",
        Router: "readonly",
        RuntimeContracts: "readonly",
        SearchState: "readonly",
        Selection: "readonly",
        SelectionBar: "readonly",
        SettingsState: "readonly",
        SettingsView: "readonly",
        ShowdownParser: "readonly",
        SlotSelection: "readonly",
        SpeciesQueries: "readonly",
        SpeciesResolver: "readonly",
        StatEditorWidget: "readonly",
        StorageMappers: "readonly",
        BuildSummarySection: "readonly",
        TeamExportFormatter: "readonly",
        TeamSurfaces: "readonly",
        TeamsView: "readonly",
        UIModels: "readonly",
        UIShared: "readonly",
      },
    },
    rules: {
      // Start conservative — catch real bugs, not style
      "no-undef": "warn",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-constant-condition": "warn",
      "no-debugger": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-extra-boolean-cast": "warn",
      "no-func-assign": "error",
      "no-inner-declarations": "warn",
      "no-unreachable": "warn",
      "use-isnan": "error",
      "valid-typeof": "error",
      "eqeqeq": ["warn", "smart"],
      "no-caller": "error",
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-wrappers": "error",
      "no-throw-literal": "warn",
      "no-self-compare": "warn",
      "no-template-curly-in-string": "warn",
    },
  },
  {
    ignores: [
      "node_modules/",
      "data/reference/",
      "userdata/",
      ".scratch/",
      "test-results/",
      "tools/fixtures/",
    ],
  },
];
